apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: storage-topic
  labels:
    strimzi.io/cluster: mkaf
spec:
  partitions: 1
  replicas: 1

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: global-id-topic
  labels:
    strimzi.io/cluster: mkaf
spec:
  partitions: 1
  replicas: 1

